[versions]
grpcVersion = "1.64.0"
jacksonVersion = "2.17.1"
guiceVersion = "7.0.0"
slf4jVersion = "1.7.36"
logbackVersion = "1.3.7"
log4jVersion = "2.20.0"
jraftVersion = "1.3.14"
rocksdbVersion = "7.1.2"
h2Version = "2.2.224"
armeriaVersion = "1.30.1"
httpasyncclientVersion = "4.1.5"
disruptorVersion = "3.3.7"
prometheusVersion = "0.16.0"
javaxVersion = "1.3.2"
hibernateValidatorVersion = "7.0.4.Final"
protobufVersion = "3.25.2"
typetoolsVersion = "0.6.3"
commonsioVersion = "2.8.0"
commonslangVersion = "2.6"
commonstextVersion = "1.10.0"
hessianVersion = "3.3.6"
jakartaelVersion = "4.0.2"
jsr305Version = "3.0.2"
jwtVersion = "0.11.5"
cronutilsVersion = "9.2.0"
affinityVersion = "3.23.3"
jakartamailVersion = "2.0.1"
jupiterVersion = "5.9.2"
javaxAnnotationVersion = "1.3.2"

[libraries]
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4jVersion" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4jVersion" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4jVersion" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logbackVersion" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jacksonVersion" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jacksonVersion" }
hibernate-validator = { group = "org.hibernate.validator", name = "hibernate-validator", version.ref = "hibernateValidatorVersion" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsioVersion" }
commons-lang = { group = "commons-lang", name = "commons-lang", version.ref = "commonslangVersion" }
javax-annotation-api = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javaxAnnotationVersion" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commonstextVersion" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305Version" }
prometheus-client = { group = "io.prometheus", name = "simpleclient", version.ref = "prometheusVersion" }
typetools = { group = "net.jodah", name = "typetools", version.ref = "typetoolsVersion" }
jakarta-el = { group = "org.glassfish", name = "jakarta.el", version.ref = "jakartaelVersion" }
affinity = { group = "net.openhft", name = "affinity", version.ref = "affinityVersion" }
cron-utils = { group = "com.cronutils", name = "cron-utils", version.ref = "cronutilsVersion" }
disruptor = { group = "com.lmax", name = "disruptor", version.ref = "disruptorVersion" }
rocksdbjni = { group = "org.rocksdb", name = "rocksdbjni", version.ref = "rocksdbVersion" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2Version" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guiceVersion" }
hessian = { group = "com.alipay.sofa", name = "hessian", version.ref = "hessianVersion" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jwtVersion" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jwtVersion" }
jraft-core = { group = "com.alipay.sofa", name = "jraft-core", version.ref = "jraftVersion" }
jraft-grpc = { group = "com.alipay.sofa", name = "rpc-grpc-impl", version.ref = "jraftVersion" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobufVersion" }
jakarta-mail = { group = "com.sun.mail", name = "jakarta.mail", version.ref = "jakartamailVersion" }
armeria = { group = "com.linecorp.armeria", name = "armeria", version.ref = "armeriaVersion" }
armeria-grpc = { group = "com.linecorp.armeria", name = "armeria-grpc", version.ref = "armeriaVersion" }
grpc-api = { group = "io.grpc", name = "grpc-api", version.ref = "grpcVersion" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version.ref = "grpcVersion" }
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpcVersion" }
grpc-services = { group = "io.grpc", name = "grpc-services", version.ref = "grpcVersion" }
grpc-netty = { group = "io.grpc", name = "grpc-netty", version.ref = "grpcVersion" }
grpc-netty-shaded = { group = "io.grpc", name = "grpc-netty-shaded", version.ref = "grpcVersion" }
httpasyncclient = { group = "org.apache.httpcomponents", name = "httpasyncclient", version.ref = "httpasyncclientVersion" }

[bundles]
log4j = ["log4j-api", "log4j-core", "log4j-slf4j-impl"]